[package]
name = "everscale-asm"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["lsp-server"]

[dependencies]
ahash = "0.8"
anyhow = "1.0"
chumsky = "1.0.0-alpha.6"
either = "1.0"
everscale-types = "0.1.0-rc.5"
hex = "0.4"
num-bigint = "0.4"
num-traits = "0.2"
pest = "2.7"
pest_derive = "2.7"
thiserror = "1.0"

[patch.crates-io]
everscale-types = { git = "https://github.com/broxus/everscale-types.git" }
